services:
  goitquotes.com:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_PORT: ${PG_PORT}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: ./bd_data
        target: /var/lib/postgresql/data
    ports:
      - 5432:${PG_PORT}


